><nav>
    <ul>
        <li><a href="home.php">Home</a></li>
        <li><a href="mail_list_signup.php">Mail Signup</a></li>
        <li><a href="mailing_list.php">Mail List</a></li>
		<li><a href="admin_login.php">Admin Login</a></li>
        <li><a href="products.php">Products</a></li>
		<li><a href="my_cart.php">My Cart</a></li>
		<li><a href="register.php">Register</a></li>
		<li><a href="sessionEnd.php">Log Out</a></li>
    </ul>
</nav>